---
dependencies: []

galaxy_info:
  role_name: amazon_ssm_agent
  author: jason_riddle
  description: "Amazon SSM Agent on Linux."
  issue_tracker_url: https://github.com/jason-riddle/ansible-role-amazon_ssm_agent/issues
  license: "MIT"
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - buster # 10
    - name: Ubuntu
      versions:
        - bionic # 18.04
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - system
    - amazon
    - aws
    - ssm
