---
- name: Ensure additional dependencies are installed (on Ubuntu < 20.04 and any other systems).
  apt:
    name: gnupg2
    state: present
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version is version('20.04', '<')

- name: Ensure additional dependencies are installed (on Ubuntu >= 20.04).
  apt:
    name: gnupg
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution_version is version('20.04', '>=')

- name: Add kubectl apt key.
  apt_key:
    url: "{{ kubectl_apt_gpg_key }}"
    state: present

- name: Add kubectl repository.
  apt_repository:
    repo: "{{ kubectl_apt_repository }}"
    state: present
    update_cache: true
