---
github_users: []
# You can specify an object with 'name' (required) and 'groups' (optional):
# - name: geerlingguy
#   groups: www-data,sudo

# Or you can specify a GitHub username directly:
# - geerlingguy
