login:
	devenv shell -- terraform login

init:
	devenv shell -- terraform init

plan:
	devenv shell -- terraform plan

fmt:
	devenv shell -- terraform fmt -recursive

check:
	devenv shell -- terraform fmt -check -recursive -diff
