---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault-helm
resources:
  - ./namespace.yaml

# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md
helmCharts:
  - name: vault
    includeCRDs: true
    valuesInline:
      minecraftServer:
        eula: true
    releaseName: vault-release
    version: 0.24.0
    repo: https://helm.releases.hashicorp.com
