---
- name: Assert that hostname is not empty.
  assert:
    that:
      - hostname | length > 0
    quiet: true

- name: Set hostname.
  hostname:
    name: "{{ hostname_name }}"
  register: hostname

- name: Reboot.
  reboot:
    reboot_timeout: 300
  when:
    - hostname is changed
