---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault
commonLabels:
  app: vault
resources:
  - ./namespace.yaml

# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md
helmCharts:
  - name: vault
    version: 0.24.0
    repo: https://helm.releases.hashicorp.com
    releaseName: vault
    valuesInline:
      server:
        affinity: ""
        ha:
          enabled: true
          raft:
            enabled: true
