---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization.  # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

  roles:
    - role: jason_riddle.hostname

  post_tasks:
    - name: Run setup facts.
      setup:

    - name: Reset ssh connection.
      meta: reset_connection

    - name: Get hostname.
      command: "hostname"
      changed_when: false
      register: hostname_command

    - name: Assert that hostname_command.stdout is {{ hostname_name }}.
      assert:
        that:
          - hostname_command.stdout == hostname_name
        fail_msg: |
          assert failed 'hostname_command.stdout == hostname_name'
          hostname_command.stdout is '{{ hostname_command.stdout }}'
          hostname_name is '{{ hostname_name }}'

    - name: Assert that ansible_hostname is {{ hostname_name }}.
      assert:
        that:
          - ansible_hostname == hostname_name
        fail_msg: |
          assert failed 'ansible_hostname == hostname_name'
          ansible_hostname is '{{ ansible_hostname }}'
          hostname_name is '{{ hostname_name }}'
