---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

commonLabels:
  app: vault

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    valuesInline:
      global:
        externalVaultAddr: "https://jasons-vault-cluster-public-vault-f2141d90.14a4e04d.z1.hashicorp.cloud:8200"
