---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure service is running as desired.
  service:
    name: "{{ amazon_ecs_agent_service_name }}"
    state: "{{ amazon_ecs_agent_service_state }}"
    enabled: "{{ amazon_ecs_agent_service_enabled }}"

- include_tasks: register.yml
  when: amazon_ecs_agent_register_agent | bool
