---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure user accounts are present.
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    createhome: true
    groups: "{{ item.groups | default(omit) }}"
    home: "/home/{{ item.name }}"
    state: present
  with_items: "{{ github_users }}"
