---
name: CI - Super-Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  schedule:
    # Run at 2am on Thursday.
    # REF: https://crontab.guru/#0_2_*_*_4
    - cron: "0 2 * * 4"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Read env vars from super-linter.env.
        run: |
          cat .github/env/super-linter.env >> "$GITHUB_ENV"

      - name: Lint code.
        uses: super-linter/super-linter/slim@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
