---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure users are present.
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    createhome: true
    groups: "{{ item.groups | default(omit) }}"
    home: "/home/{{ item.name }}"
    state: present
  with_items: "{{ github_users }}"

- name: Ensure authorized keys for are present.
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ github_keys_url }}"
    manage_dir: true
    exclusive: "{{ github_users_authorized_keys_exclusive }}"
  with_items: "{{ github_users }}"
